# Generated by Django 4.0 on 2024-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.TextField(default=''),
        ),
    ]
