# Generated by Django 4.0 on 2024-02-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='let_anon_users_see_resume',
            field=models.BooleanField(default=False),
        ),
    ]
